// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoLdMPS0Qb5BgrAI7IBaIyEBbTvHAabkU',
    appId: '1:732802152050:web:0d639889dd05841fff34eb',
    messagingSenderId: '732802152050',
    projectId: 'spotify1605',
    authDomain: 'spotify1605.firebaseapp.com',
    storageBucket: 'spotify1605.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUTBHzXg0o33lOOio6sLsgApAF_CYNJWQ',
    appId: '1:732802152050:android:b509f7f268bfcf2fff34eb',
    messagingSenderId: '732802152050',
    projectId: 'spotify1605',
    storageBucket: 'spotify1605.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDSBtuGv8fpLUiGhKceJQRSAKlMT1Qzw4',
    appId: '1:732802152050:ios:2234f38bdc30e656ff34eb',
    messagingSenderId: '732802152050',
    projectId: 'spotify1605',
    storageBucket: 'spotify1605.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDSBtuGv8fpLUiGhKceJQRSAKlMT1Qzw4',
    appId: '1:732802152050:ios:2234f38bdc30e656ff34eb',
    messagingSenderId: '732802152050',
    projectId: 'spotify1605',
    storageBucket: 'spotify1605.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoLdMPS0Qb5BgrAI7IBaIyEBbTvHAabkU',
    appId: '1:732802152050:web:4a8d9a45a883177eff34eb',
    messagingSenderId: '732802152050',
    projectId: 'spotify1605',
    authDomain: 'spotify1605.firebaseapp.com',
    storageBucket: 'spotify1605.firebasestorage.app',
  );
}
